items = [
    {'model': '7', 'storage': '32', 'id': 'MN8X2X/A', 'finish': 'Black'},
    {'model': '7', 'storage': '32', 'id': 'MN8Y2X/A', 'finish': 'Silver'},
    {'model': '7', 'storage': '32', 'id': 'MN902X/A', 'finish': 'Gold'},
    {'model': '7', 'storage': '32', 'id': 'MN912X/A', 'finish': 'RoseGold'},
    {'model': '7', 'storage': '128', 'id': 'MN962X/A', 'finish': 'JetBlack'},
    {'model': '7', 'storage': '128', 'id': 'MN922X/A', 'finish': 'Black'},
    {'model': '7', 'storage': '128', 'id': 'MN932X/A', 'finish': 'Silver'},
    {'model': '7', 'storage': '128', 'id': 'MN942X/A', 'finish': 'Gold'},
    {'model': '7', 'storage': '128', 'id': 'MN952X/A', 'finish': 'RoseGold'},
    {'model': '7', 'storage': '256', 'id': 'MN9C2X/A', 'finish': 'JetBlack'},
    {'model': '7', 'storage': '256', 'id': 'MN972X/A', 'finish': 'Black'},
    {'model': '7', 'storage': '256', 'id': 'MN982X/A', 'finish': 'Silver'},
    {'model': '7', 'storage': '256', 'id': 'MN992X/A', 'finish': 'Gold'},
    {'model': '7', 'storage': '256', 'id': 'MN9A2X/A', 'finish': 'RoseGold'},

    {'model': '7+', 'storage': '32', 'id': 'MNQM2X/A', 'finish': 'Black'},
    {'model': '7+', 'storage': '32', 'id': 'MNQN2X/A', 'finish': 'Silver'},
    {'model': '7+', 'storage': '32', 'id': 'MNQP2X/A', 'finish': 'Gold'},
    {'model': '7+', 'storage': '32', 'id': 'MNQQ2X/A', 'finish': 'RoseGold'},
    {'model': '7+', 'storage': '128', 'id': 'MN4V2X/A', 'finish': 'JetBlack'},
    {'model': '7+', 'storage': '128', 'id': 'MN4M2X/A', 'finish': 'Black'},
    {'model': '7+', 'storage': '128', 'id': 'MN4P2X/A', 'finish': 'Silver'},
    {'model': '7+', 'storage': '128', 'id': 'MN4Q2X/A', 'finish': 'Gold'},
    {'model': '7+', 'storage': '128', 'id': 'MN4U2X/A', 'finish': 'RoseGold'},
    {'model': '7+', 'storage': '256', 'id': 'MN512X/A', 'finish': 'JetBlack'},
    {'model': '7+', 'storage': '256', 'id': 'MN4W2X/A', 'finish': 'Black'},
    {'model': '7+', 'storage': '256', 'id': 'MN4X2X/A', 'finish': 'Silver'},
    {'model': '7+', 'storage': '256', 'id': 'MN4Y2X/A', 'finish': 'Gold'},
    {'model': '7+', 'storage': '256', 'id': 'MN502X/A', 'finish': 'RoseGold'}
]
